---
- name: el6 | Local Install {{ ansible_distribution }}
  become: yes
  yum:
    name: http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-2.noarch.rpm
    #command: yum localinstall http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-2.noarch.rpm -y
    state: installed
    update_cache: yes
    when: ansible_distribution == "CentOS"

- name: el6 | Local Install {{ ansible_distribution }}
  become: yes
  yum:
    name: http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-redhat94-9.4-2.noarch.rpm
    state: installed
    update_cache: yes
  when: ansible_distribution == "RedHat"

- name: el6 | Install postgresql94
  become: yes
  yum:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - postgresql94-server
    - postgresql94-contrib
    - postgresql94-devel

- name: el6 | Initialize Postgresql-9.4
  become: yes
  command: service postgresql-9.4 initdb

- name: el6 | MD5-encrypted password for postgres 1
  become: yes
  command: 'sed -i "s/\(host.*all.*all.*127.0.0.1\/32.*\)ident/\1md5/" /var/lib/pgsql/9.4/data/pg_hba.conf'
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"


- name: el6 | MD5-encrypted password for postgres 2
  become: yes
  command: 'sed -i "s/\(host.*all.*all.*::1\/128.*\)ident/\1md5/" /var/lib/pgsql/9.4/data/pg_hba.conf'
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: el6 | Start and Enable Postgresql-9.4
  become: yes
  service:
    name: postgresql-9.4
    state: started
